name: pizza_repository
description: TheRepo that handles pizzas
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.8
  # firebase_auth: ^5.6.2
  # cloud_firestore: ^5.6.11
  # firebase_storage: ^12.4.9
  # rxdart: ^0.28.0
  # path: ^1.9.1
  # equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true